appName: node-order-app
namespace: dev
serviceAccount:
  create: true
  name: node-order-app-sa
  roleArn: arn:aws:iam::259183055744:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: false
  path: /metrics
  interval: 30s
replicaCount: 2
image:
  repository: paragon40/node_order_app
  tag: 79ecd1d6d6-2026-09-16-10-38-28
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 15
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 70
  memory: 70
meta:
  staticFingerprint: e242e5b5f0c9c672fd2175e1b951e276bdede1ea61b6512db5568d9ce5840954
  generatedAt: 2026-09-16T11:48:45Z
  source: build-pipeline
labels:
  compute: fargate
