apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:+iii7Csk,iv:ugjIE6y8NgAHhX4wDM4ZurArfaX6RYpLqQusGK2x6WE=,tag:IUeQNYFoJotnqiuRuSTFdA==,type:str]
    admin-password: ENC[AES256_GCM,data:g0358cKw,iv:JMrMoHwmXPpuzpGKZo2mK+AD5kllTvAXDmNGWSoZABE=,tag:NspfZJSTc4q/OFg/hPkXTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQWpMU2d5VGw5YVlKREtK
            b05jYXNrR3JMMFFCSml5MEczMEZMZnVFdlNnCmdaQVJkakZ2OG4ya0gwYmRsOXJT
            eXp3NjBab1IyeCtBUDhCWWx2LzB2bk0KLS0tIDJDTHZ6YnpyTUZmN0pzWnVuZUtO
            ejhiQ09qOTRwSk1uaHFQRzJ2R2VLZUkKAgpbsSE90HqZSajV0bqeL4fCfacPFspw
            EhEFWxvYC5vQq1yA4qw+GLQQ/JVBg0fNeLCkUURP31Bw8ou5M769tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19u9pmsn4845rghpmrmfh4vnvgm7jwad2njacfq5td9nnu7jawfvqr88alg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T12:52:45Z"
    mac: ENC[AES256_GCM,data:aO+cGVsoCeeRJtaSHAINkrJZpU1WxfGTt1KZLRQ83egEi6wNogcf3F5dulPosAs5lx9EFwHKbZr0IOCWoSSg+mtNZZQUrIzSv0AarC4mD6VSRRHViqYyvNv1a3rFHibnyjheqOM+jcnFqwsfMpCyGZDFCmCSVSTIwAxeubAQXv4=,iv:7YXDwCe6lfVfrJfCuzim6EuGscb297HWbCxGuN9ZIGw=,tag:1Qu436pyQRwQcYRuG3LjsA==,type:str]
    version: 3.13.1
