server {
    listen 80;
    server_name sys-monitor.rundailytest.site;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name sys-monitor.rundailytest.site;

    ssl_certificate /etc/letsencrypt/live/sys-monitor.rundailytest.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sys-monitor.rundailytest.site/privkey.pem;

    # -----------------------
    # GitHub Webhook
    # -----------------------
    location /webhook/github {
        proxy_pass http://127.0.0.1:3000;
        include proxy_params;
    }

    # -----------------------
    # Grafana (FIXED)
    # -----------------------
    location /grafana/ {
        proxy_pass http://127.0.0.1:3001/;
        include proxy_params;
    }

    # -----------------------
    # Prometheus
    # -----------------------
    location /prometheus/ {
        proxy_pass http://127.0.0.1:9090/;
        include proxy_params;
    }
}
