appName: urlshortener
namespace: dev
serviceAccount:
  create: true
  name: urlshortener-sa
  roleArn: arn:aws:iam::532918215760:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: false
  path: /metrics
  interval: 30s
replicaCount: 2
image:
  repository: paragon40/url_shortener
  tag: bbf7883ba408305cf8ce5e7b5aaa994961fadfa9-1780923208
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10005
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /api/live
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 15
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 70
  memory: 70
meta:
  staticFingerprint: d882d65204ed4afd42b1d002d2189eff2847433e8ecf57ebe372615ceae7d8b1
  generatedAt: 2026-06-11T11:44:23Z
  source: build-pipeline
storage:
  volumes:
    - name: urlshortener-volume
      emptyDir: {}
  volumeMounts:
    - name: urlshortener-volume
      mountPath: /data
labels:
  compute: fargate
