appName: metrics
namespace: dev
serviceAccount:
  create: true
  name: metrics-sa
  roleArn: arn:aws:iam::532918215760:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
replicaCount: 2
image:
  repository: paragon40/metrics_app
  tag: bbf7883ba408305cf8ce5e7b5aaa994961fadfa9-1780923208
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10009
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /live
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 70
  memory: 70
meta:
  staticFingerprint: 6eb65282886a0603f8c86255c84251d376fa95d72df49a6392d9bc346965da9f
  generatedAt: 2026-06-11T11:44:22Z
  source: build-pipeline
storage:
  volumes:
    - name: metrics
      emptyDir: {}
  volumeMounts:
    - name: metrics
      mountPath: /data
labels:
  compute: fargate
