appName: python-cicd
namespace: dev
serviceAccount:
  create: true
  name: python-cicd-sa
  roleArn: arn:aws:iam::259183055744:role/kubapp-dev-app-pods-role
serviceMonitor:
  enabled: true
  path: /metrics
  interval: 30s
replicaCount: 2
image:
  repository: paragon40/py_cicd_app
  tag: 79ecd1d6d6-2026-09-16-10-38-41
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: {}
securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    runAsNonRoot: true
    runAsUser: 10006
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
probes:
  readiness:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 15
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 70
  memory: 70
meta:
  staticFingerprint: 2a0f77290cb52fb4a241c71c8b5c6ce973f95393a379e2c2983f831efd0126ba
  generatedAt: 2026-09-16T11:48:46Z
  source: build-pipeline
storage:
  volumes:
    - name: edgepaas-vol
      emptyDir: {}
  volumeMounts:
    - name: edgepaas-vol
      mountPath: /tmp
nodeSelector:
  compute: ec2
tolerations:
  - key: compute
    operator: Equal
    value: ec2
    effect: NoSchedule
