apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}

    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.name }}-pvc

