apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubapp
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/paragon40/kubapp.git
        revision: main
        directories:
          - path: gitops/envs/dev/apps/*

  template:
    metadata:
      name: "{{path[4]}}-{{path[2]}}"
      labels:
        env: "{{path[2]}}"
        app: "{{path[4]}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/paragon40/kubapp.git
        targetRevision: main

        path: gitops/charts/apps

        helm:
          valueFiles:
            - "../../../{{path}}/values.yaml"
            # - gitops/envs/{{path[1]}}/{{path[2]}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[2]}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
