apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - namespace: dev
            env: dev
            stack: values
          - namespace: monitoring
            env: dev
            stack: monitoring
          - namespace: argocd
            env: dev
            stack: argocd

  template:
    metadata:
      name: "ingress-{{env}}-{{stack}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/paragon40/kubapp.git
        targetRevision: main
        path: gitops/charts/ingress
        helm:
          valueFiles:
            - "../../ingress/{{env}}/{{stack}}.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
