name: Activate Pipeline Workflows

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

      mode:
        required: true
        default: full
        type: choice
        options:
          - full
          - build
          - rollback
          - cleanup

permissions:
  contents: write
  actions: read
  id-token: write
  pull-requests: write
  security-events: write

concurrency:
  group: activate-pipeline-${{ inputs.env }}
  cancel-in-progress: false

jobs:

  ci:
    if: ${{ inputs.mode == 'full' || inputs.mode == 'build' }}
    uses: ./.github/workflows/ci.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit

  build:
    if: ${{ inputs.mode == 'full' || inputs.mode == 'build' }}
    needs: ci
    uses: ./.github/workflows/build.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit

  deploy:
    if: ${{ inputs.mode == 'full' || inputs.mode == 'build' }}
    needs: build
    uses: ./.github/workflows/add_new_app.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit

  setup_argocd:
    if: ${{ inputs.mode == 'full' }}
    needs: deploy
    uses: ./.github/workflows/setup_argocd.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit

  validate_gitops_build:
    if: ${{ inputs.mode == 'build' }}
    needs: deploy
    uses: ./.github/workflows/validate_gitops.yml
    with:
      env: ${{ inputs.env }}

  validate_gitops_full:
    if: ${{ inputs.mode == 'full' }}
    needs: setup_argocd
    uses: ./.github/workflows/validate_gitops.yml
    with:
      env: ${{ inputs.env }}

  verify_runtime:
    if: ${{ inputs.mode == 'full' }}
    needs: validate_gitops_full
    uses: ./.github/workflows/verify_runtime.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit

  cleanup_only:
    if: ${{ inputs.mode == 'cleanup' }}
    uses: ./.github/workflows/clean_argocd.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit

  latest_stable_deploy:
    if: ${{ inputs.mode == 'rollback' }}
    uses: ./.github/workflows/get_stable_deploy.yml
    with:
      env: ${{ inputs.env }}

  rollback:
    if: ${{ inputs.mode == 'rollback' }}
    needs: latest_stable_deploy
    uses: ./.github/workflows/rollback.yml
    with:
      env: ${{ inputs.env }}
      commit: ${{ needs.latest_stable_deploy.outputs.stable_commit }}
      tag: ${{ needs.latest_stable_deploy.outputs.stable_tag }}
