name: Inspect App Artifacts

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GH CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get latest successful build run
        id: run
        run: |
          RUN_ID=$(gh run list \
            --workflow "build.yml" \
            --status success \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId'
          )

          if [[ -z "$RUN_ID" ]]; then
             echo "❌ Run_id Not found"
             exit 1
          fi
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: List artifacts for run
        run: |
          gh api repos/${{ github.repository }}/actions/runs/${{ steps.run.outputs.run_id }}/artifacts \
            | jq '.artifacts[] | {name, size_in_bytes, expired}'

      - name: Download artifact (registry-user_app)
        run: |
          mkdir -p artifacts
          gh run download ${{ steps.run.outputs.run_id }} \
            --name "registry-user_app" \
            --dir artifacts

      - name: Debug downloaded structure
        run: |
          echo "===== FULL TREE ====="
          ls -R artifacts

      - name: Show artifact contents
        run: |
          set -euo pipefail
          echo "===== Discovering files ====="
          FILES=$(find artifacts -type f)
          if [[ -z "$FILES" ]]; then
            echo "❌ No files found in artifacts"
            exit 1
          fi

          echo "✅ Files found:"
          echo "$FILES"

          for each in $FILES; do
            echo "========= $each ======"
            ls -l "$each"
            echo "========= CONTENT ====="
            cat "$each" || true
          done
