name: Argocd And Gitops Bootstrap

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      env:
        description: Environment
        required: true
        default: dev
        type: choice
        options: [dev, prod]

permissions:
  id-token: write
  contents: read

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install SOPS
        run: |
          curl -L -o sops https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/sops

      - name: Setup AGE key
        run: |
          mkdir -p ~/.config/sops/age
          echo "${{ secrets.AGE_PRIVATE_KEY }}" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
          test -s ~/.config/sops/age/keys.txt || {
            echo "❌ AGE key missing"
            exit 1
          }

      - name: Setup kubeconfig
        run: |
          set -e

          aws eks update-kubeconfig \
            --region ${{ vars.AWS_REGION }} \
            --name kubapp-dev

          export KUBECONFIG=~/.kube/config
          echo "✅ kubeconfig created"
          kubectl cluster-info

      - name: Check
        run: |
          set -e
          echo "=== auth test ==="
          kubectl auth can-i get pods -A || true

      - name: Check Readiness
        run: bash scripts/gitops/check_cluster.sh

      - name: Apply ArgoCD GitHub App secret
        run: |
          python scripts/gitops/apply_secrets.py
        env:
           PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}
           APP_ID: ${{ secrets.APP_ID_GITHUB }}
           REPO_URL: ${{ vars.REPO_URL }}

      - name: Verify ArgoCD namespace access
        run: kubectl get ns argocd

      - name: Verify secret exists
        run: kubectl get secret -n argocd | grep github || true

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Ensure helm is isntalled
        run: |
          if ! command -v helm >/dev/null 2>&1; then
            sudo snap install helm --classic
          fi

      - name: Install Metrics Server for HPA
        run: |
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
          helm upgrade --install metrics-server metrics-server/metrics-server \
            -n kube-system \
            --create-namespace

      - name: Run GitOps bootstrap
        env:
          REPO_URL: "https://github.com/${{ github.repository }}.git"
        run:  |
          echo "REPO_URL=$REPO_URL"
          chmod +x scripts/gitops/bootstrap_gitops.sh
          bash scripts/gitops/bootstrap_gitops.sh

      - name: Get Metadata from Terraform
        working-directory: iac/infra
        env:
          ENV: "${{ github.event.inputs.env }}"
        run: |
          set -euo pipefail
          terraform init -reconfigure -backend-config="envs/${ENV}/backend.hcl"
          DOMAIN=$(terraform output -raw domain 2>/dev/null || true)
          CERT_ARN=$(terraform output -raw cert_arn 2>/dev/null || true)
          ZONE_ID=$(terraform output -raw dns_zone_id 2>/dev/null || true)

          if [[ -z "$DOMAIN" ]]; then
            echo "❌ DOMAIN is empty"
            exit 1
          fi

          if [[ -z "$CERT_ARN" ]]; then
            echo "❌ CERT ARN is empty"
            exit 1
          fi

          if [[ -z "$ZONE_ID" ]]; then
            echo "❌ ZONE_ID is empty"
            exit 1
          fi

          echo "DOMAIN Found: $DOMAIN"
          echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
          echo "CERT_ARN Found: $CERT_ARN"
          echo "CERT_ARN=$CERT_ARN" >> $GITHUB_ENV
          echo "ZONE_ID Found: $ZONE_ID"
          echo "ZONE_ID=$ZONE_ID" >> $GITHUB_ENV

      - name: Ensure Route53 is synced
        env:
          ENV: "${{ github.event.inputs.env }}"
          DOMAIN: "${{ env.DOMAIN }}"
          CERT_ARN: "${{ env.CERT_ARN }}"
          ZONE_ID: "${{ env.ZONE_ID }}"
          AWS_REGION: "${{ env.AWS_REGION }}"
        run: |
          set -euo pipefail
          for i in {1..8}; do
            echo "Setting up route53 for Domain if new..."
            if bash scripts/gitops/sync_route53.sh; then
              echo "✅ Success on attempt $i"
              break
            else
              echo "ALB not ready yet, retrying..."
              sleep 5
            fi
            echo "❌ Route53 sync failed after $i attempts"
          done
          echo "End of Workflow!"
