name: Terraform Drift Checker

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (dev/prod)"
        required: true
        type: choice
        options:
          - dev
          - prod

      folders:
        description: "Terraform folders (comma-separated, e.g. network,iam,xyz)"
        required: true
        default: ""

jobs:
  drift-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Parse inputs
        id: parse
        run: |
          echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          echo "FOLDERS=${{ github.event.inputs.folders }}" >> $GITHUB_ENV

      - name: Run Drift Detection
        run: |
          set -euo pipefail

          IFS=',' read -ra DIRS <<< "$FOLDERS"

          echo "======================================"
          echo "TF DRIFT SCAN START"
          echo "ENV: $ENV"
          echo "FOLDERS: $FOLDERS"
          echo "======================================"

          mkdir -p /tmp/drift-logs

          for dir in "${DIRS[@]}"; do
            dir=$(echo "$dir" | xargs)

            TF_PATH="iac/$dir"

            echo ""
            echo "--------------------------------------"
            echo "Scanning: $TF_PATH"
            echo "--------------------------------------"

            if [[ ! -d "$TF_PATH" ]]; then
              echo "❌ Folder not found: $TF_PATH"
              continue
            fi

            cd "$TF_PATH"

            terraform init -input=false -no-color

            set +e
            terraform plan -detailed-exitcode -no-color > /tmp/drift-logs/${dir}.log
            EXIT_CODE=$?
            set -e

            if [[ $EXIT_CODE -eq 0 ]]; then
              echo "✅ No drift detected in $dir"
              STATUS="NO_DRIFT"

            elif [[ $EXIT_CODE -eq 2 ]]; then
              echo "⚠️ Drift detected in $dir"
              STATUS="DRIFT"

            else
              echo "❌ Terraform error in $dir"
              STATUS="ERROR"
            fi

            echo "[$dir] => $STATUS" >> /tmp/drift-summary.txt

            cd - >/dev/null
          done

      - name: Show Summary
        run: |
          echo ""
          echo "=============================="
          echo "DRIFT SUMMARY"
          echo "=============================="
          cat /tmp/drift-summary.txt || echo "No summary available"

