name: Runtime Verification

on:
  workflow_run:
    workflows:
      - "Runtime Image Update"
      - "Add New App (GitOps Provisioning)"
      - "Remove App"
    types: [completed]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      ####################################################
      # AUTH
      ####################################################
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_GITHUB }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: paragon40/kubapp
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup kubeconfig
        run: |
          set -e

          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name kubapp-dev

          export KUBECONFIG=~/.kube/config

          echo "✅ kubeconfig created"

          kubectl cluster-info


      ####################################################
      # INSTALL TOOLS
      ####################################################
      - name: Install dependencies
        run: |
          set -euo pipefail

          sudo apt-get update
          sudo apt-get install -y jq curl

          # kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

          # argocd
          curl -sSL -o argocd \
            https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      ####################################################
      # LOAD STATE
      ####################################################
      - name: Load ENV from state
        run: |
          set -euo pipefail

          STATE_FILE="gitops/state/current.json"

          if [[ ! -f "$STATE_FILE" || ! -s "$STATE_FILE" ]]; then
            echo "❌ Missing state file"
            exit 1
          fi

          ENV=$(jq -r '.env' "$STATE_FILE")

          if [[ -z "$ENV" || "$ENV" == "null" ]]; then
            echo "❌ Invalid ENV in state file"
            exit 1
          fi

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "Detected ENV: $ENV"

      ####################################################
      # PRECHECKS
      ####################################################
      - name: Run prechecks
        run: |
          bash scripts/prechecks.sh "${{ env.ENV }}"

      ####################################################
      # VERIFY RUNTIME
      ####################################################
      - name: Print secrets
        run: |
          echo "SERVER=${{ secrets.ARGOCD_SERVER }}"

      - name: Run postchecks (deep verification)
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          ENV="${{ env.ENV }}"
          #DOM="${{ secrets.DOMAIN }}"
          DOM="rundailytest.online"
          export ARGOCD_OPTS="--server $ARGOCD_SERVER --auth-token $ARGOCD_AUTH_TOKEN"
          bash scripts/postchecks.sh "$ENV" "$DOM"

      # FAILURE HANDLER
      - name: Suggest rollback
        if: failure()
        run: |
          ENV="${{ env.ENV }}"
          git fetch --tags

          PREV=$(git tag --list "stable-${ENV}-*" --sort=-creatordate | sed -n '2p')

          if [[ -n "$PREV" ]]; then
            echo "⚠️ Rollback recommended:"
            echo "git checkout $PREV"
          else
            echo "⚠️ No previous stable tag found"
          fi
          exit 0

      - name: Create Snapshot for Commit Tag
        run: |
          set -euo pipefail
          ENV="${{ env.ENV }}"
          COMMIT="$(git rev-parse HEAD)"
          RUN_ID="${{ github.run_id }}"
          TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          DATE="$(date +%Y%m%d-%H%M%S)"
          SERVICE_COUNT=$(find gitops/registry/$ENV -name "*.json" | wc -l)

          DIR="snapshots/deploys"
          FILE="$DIR/${ENV}-${DATE}.json"
          mkdir -p "$DIR"

          jq -n \
            --arg env "$ENV" \
            --arg commit "$COMMIT" \
            --arg run_id "$RUN_ID" \
            --arg services "$SERVICE_COUNT" \
            --arg time "$TS" \
          '{
              env: $env,
              commit: $commit,
              run_id: $run_id,
              services: ($services | tonumber),
              timestamp: $time
           }' > "$FILE"

           echo "SNAPSHOT_FILE=$FILE" >> $GITHUB_ENV
           echo "Snapshot created:"
           cat "$FILE"

      - name: Tag Commit as stable
        run: |
          set -euo pipefail
          ENV="${{ env.ENV }}"
          COMMIT="$(git rev-parse HEAD)"
          TIME="$(date +%Y%m%d-%H%M%S)"
          SHORT="$(git rev-parse --short HEAD)"
          TAG="stable-${ENV}-${TIME}-${SHORT}"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag -a "$TAG" -m "Stable deployment: [$ENV] || Commit=$COMMIT || Run_ID=${{ github.run_id }} || time=$TIME"
          git push origin "$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "✅ Stable tag created: $TAG"


      - name: Upload deployment snapshot
        uses: actions/upload-artifact@v4
        with:
          name: deployment-snapshot
          path: ${{ env.SNAPSHOT_FILE }}
