namespace: dev
ingress:
  name: kubapp-dev-alb
  className: alb
  baseDomain: rundailytest.online
  enableSubdomainRouting: true
  certificateArn: arn:aws:acm:us-east-1:532918215760:certificate/88753851-e3e6-4911-94ce-7802a721aa41
  annotations:
    scheme: internet-facing
    targetType: ip
    healthcheckPath: /
    listenPorts:
      - HTTP: 80
      - HTTPS: 443
    group: kubapp-shared
services:
  - name: weather
    enabled: true
    port: 80
  - name: metrics
    enabled: true
    port: 80
  - name: admin
    port: 80
    enabled: true
  - name: urlshortener
    enabled: true
    port: 80
