namespace: dev
ingress:
  name: kubapp-dev-alb
  className: alb
  baseDomain: rundailytest.online
  enableSubdomainRouting: true
  certificateArn: arn:aws:acm:us-east-1:259183055744:certificate/ae2e8f24-8c4e-49e3-acaf-37ffdd953743
  annotations:
    scheme: internet-facing
    targetType: ip
    healthcheckPath: /
    listenPorts:
      - HTTP: 80
      - HTTPS: 443
    group: kubapp-shared
services:
  - name: node-order-app
    enabled: true
    port: 80
  - name: py-cicd-app
    enabled: true
    port: 80
  - name: python-cicd
    enabled: true
    port: 80
